name: Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'build/*'
      - 'os/*'
      - 'boot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          ./dist.sh
